<?php
/**
 * ╔══════════════════════════════════════════════════════════════════════════════╗
 * ║                     صرح الإتقان - SARH AL-ITQAN                              ║
 * ║                     Database Configuration                                    ║
 * ╠══════════════════════════════════════════════════════════════════════════════╣
 * ║  Generated by Installation Wizard on: 2026-01-16 13:28:07
 * ╚══════════════════════════════════════════════════════════════════════════════╝
 */

// Prevent direct access
if (!defined('SARH_SYSTEM')) {
    define('SARH_SYSTEM', true);
}

// =====================================================
// إعدادات قاعدة البيانات - Hostinger (الإنتاج)
// Database Configuration - Production Server
// =====================================================
define('DB_HOST', 'localhost');
define('DB_NAME', 'u307296675_101');
define('DB_USER', 'u307296675_101');
define('DB_PASS', 'Goolbx512!!');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATION', 'utf8mb4_unicode_520_ci');   


/**
 * فئة الاتصال بقاعدة البيانات
 * Database Connection Class (Singleton Pattern)
 */
class Database {
    private static ?PDO $instance = null;
    private static array $options = [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
        PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_520_ci",
        PDO::ATTR_PERSISTENT         => false
    ];

    /**
     * منع إنشاء نسخ جديدة
     */
    private function __construct() {}
    private function __clone() {}

    /**
     * الحصول على اتصال قاعدة البيانات
     * Get database connection instance
     * 
     * @return PDO
     * @throws PDOException
     */
    public static function getInstance(): PDO {
        if (self::$instance === null) {
            try {
                $dsn = sprintf(
                    "mysql:host=%s;dbname=%s;charset=%s",
                    DB_HOST,
                    DB_NAME,
                    DB_CHARSET
                );
                
                self::$instance = new PDO($dsn, DB_USER, DB_PASS, self::$options);
                
                // تعيين المنطقة الزمنية للسعودية
                self::$instance->exec("SET time_zone = '+03:00'");
                
            } catch (PDOException $e) {
                // تسجيل الخطأ بدون عرض تفاصيل حساسة
                error_log("Database Connection Error: " . $e->getMessage());
                
                if (defined('DEBUG_MODE') && DEBUG_MODE === true) {
                    throw new PDOException("خطأ في الاتصال بقاعدة البيانات: " . $e->getMessage());
                } else {
                    throw new PDOException("خطأ في الاتصال بقاعدة البيانات. يرجى المحاولة لاحقاً.");
                }
            }
        }
        
        return self::$instance;
    }

    /**
     * اختصار للحصول على الاتصال
     * Shorthand to get connection
     * 
     * @return PDO
     */
    public static function connect(): PDO {
        return self::getInstance();
    }

    /**
     * إغلاق الاتصال (للاستخدام في نهاية السكربت إذا لزم الأمر)
     * Close connection
     */
    public static function disconnect(): void {
        self::$instance = null;
    }

    /**
     * تنفيذ استعلام مع معاملات
     * Execute query with parameters
     * 
     * @param string $sql
     * @param array $params
     * @return PDOStatement
     */
    public static function query(string $sql, array $params = []): PDOStatement {
        $stmt = self::getInstance()->prepare($sql);
        $stmt->execute($params);
        return $stmt;
    }

    /**
     * جلب صف واحد
     * Fetch single row
     * 
     * @param string $sql
     * @param array $params
     * @return array|false
     */
    public static function fetchOne(string $sql, array $params = []): array|false {
        return self::query($sql, $params)->fetch();
    }

    /**
     * جلب جميع الصفوف
     * Fetch all rows
     * 
     * @param string $sql
     * @param array $params
     * @return array
     */
    public static function fetchAll(string $sql, array $params = []): array {
        return self::query($sql, $params)->fetchAll();
    }

    /**
     * جلب قيمة واحدة
     * Fetch single value
     * 
     * @param string $sql
     * @param array $params
     * @return mixed
     */
    public static function fetchValue(string $sql, array $params = []): mixed {
        return self::query($sql, $params)->fetchColumn();
    }

    /**
     * إدراج سجل والحصول على المعرف
     * Insert and get last ID
     * 
     * @param string $table
     * @param array $data
     * @return int
     */
    public static function insert(string $table, array $data): int {
        $columns = implode(', ', array_keys($data));
        $placeholders = ':' . implode(', :', array_keys($data));
        
        $sql = "INSERT INTO {$table} ({$columns}) VALUES ({$placeholders})";
        self::query($sql, $data);
        
        return (int) self::getInstance()->lastInsertId();
    }

    /**
     * تحديث سجلات
     * Update records
     * 
     * @param string $table
     * @param array $data
     * @param string $where
     * @param array $whereParams
     * @return int Affected rows
     */
    public static function update(string $table, array $data, string $where, array $whereParams = []): int {
        $setParts = [];
        foreach (array_keys($data) as $column) {
            $setParts[] = "{$column} = :{$column}";
        }
        $setString = implode(', ', $setParts);
        
        $sql = "UPDATE {$table} SET {$setString} WHERE {$where}";
        $stmt = self::query($sql, array_merge($data, $whereParams));
        
        return $stmt->rowCount();
    }

    /**
     * حذف سجلات
     * Delete records
     * 
     * @param string $table
     * @param string $where
     * @param array $params
     * @return int Affected rows
     */
    public static function delete(string $table, string $where, array $params = []): int {
        $sql = "DELETE FROM {$table} WHERE {$where}";
        $stmt = self::query($sql, $params);
        
        return $stmt->rowCount();
    }

    /**
     * بدء معاملة
     * Begin transaction
     */
    public static function beginTransaction(): bool {
        return self::getInstance()->beginTransaction();
    }

    /**
     * تأكيد المعاملة
     * Commit transaction
     */
    public static function commit(): bool {
        return self::getInstance()->commit();
    }

    /**
     * التراجع عن المعاملة
     * Rollback transaction
     */
    public static function rollback(): bool {
        return self::getInstance()->rollBack();
    }
}

/**
 * دالة مساعدة للحصول على اتصال قاعدة البيانات
 * Helper function to get database connection
 * 
 * @return PDO
 */
function db(): PDO {
    return Database::getInstance();
}
